### ISSUE TITLE
Arguments and customizable line separator

### ISSUE THREAD

**Issue by GasDauMin** [end2endzone/ShellAnything#87] opened 2021-01-03 21:22 UTC
I sometimes miss the ability to choose whatever separator I want when selecting multiple files or directories. What do you think about posibility use **line.separator** not as a constant but as a value dependent on the scope of the definition. For example default value can be "\r\n", but if we overwrite **line.separator** value inside the menu that menu item and the child items will inherit the rewritten value. 

Maybe this may sound complicated, but parameters separation requires flexibility in most situations. For example, in my problematic case programs looking for semicolon separator and I lack imagination on how to deal with that. :-)

**Comment by end2endzone** [comment] 2021-01-04 13:05
Is this a duplicate of #52 ? The documentation for `selection.multi.separator` is available in the [User Manual, section selection.multi.separator property](https://github.com/end2endzone/ShellAnything/blob/master/UserManual.md#selectionmultiseparator-property). 

Basically, you set the property to define a custom separator, run your action and then restore the separator property. For example:
```xml
<actions>
  <property name="selection.multi.separator" value=";" />
  <exec path="myprogram.exe" arguments="${selection.path}" />
  <property name="selection.multi.separator" value="${line.separator}" />
</actions>
```

Please advise if this issue is a duplicate or how your use case differs from the the existing solution. If the existing solution is solving your issue, set the `duplicate` label and close the issue.

**Comment by GasDauMin** [comment] 2021-01-04 15:47
Oh, okay. So I will have to read the user guide again. For me, that setting is enough. Thank You.

**Closed** 2021-01-04 15:49 UTC
Labels: duplicate, enhancement
