### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by Unknow0059** [end2endzone/ShellAnything#148] opened 2024-04-26 13:35 UTC
**Describe the bug**
I went to Programs and Features (appwiz.cpl) to uninstall ShellAnything and the uninstall process failed with an error dialog,
```
There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  
```
I also tried running the initial MSI file used to install it to uninstall it, same error.

**Screenshots**
![image](https://github.com/end2endzone/ShellAnything/assets/25656892/647534d0-c04f-46e5-8c73-e340e0a5c831)

**Environment**
 - Windows 10 Enterprise 2009 19045.4291
 - 
**Additional context**
The motive to uninstall ShellAnything is that it does not support #73 which is the reason I sought such a program.

**Comment by end2endzone** [comment] 2024-04-27 16:40
Hi. Thank you for reporting this issue and letting me know why you did not like it.

The uninstaller will try to run regsvr32.exe (see [WIX.extra.in, line 39](https://github.com/end2endzone/ShellAnything/blob/master/wix/WIX.extra.in#L39)) to unregister the shell extension before it can be uninstalled. This is mandatory because Windows File Explorer will have a hook/hold on ShellAnything's shell extension dll file. You must first force File Explorer to release the hook on the dll first. However, my expectations are that the Windows Installer should have detected this, and prevented the execution with a popup such as this:

![image](https://github.com/end2endzone/ShellAnything/assets/31753093/79d99f67-f431-4f85-aa2e-56cb54a97526)


Before running the uninstaller, you can manually unregister the shell extension following the uninstall instructions specified in [INSTALL.md](https://github.com/end2endzone/ShellAnything/blob/master/INSTALL.md#uninstall). If done correctly, you should also be able to uninstall without having to reboot your system.

To clean up your system's registry, I suggest that you reinstall the application and uninstall following the instructions in [INSTALL.md](https://github.com/end2endzone/ShellAnything/blob/master/INSTALL.md#uninstall).

Let me know how it went.
Close this issue if this has resolved your issue.

**Comment by Unknow0059** [comment] 2024-04-29 18:19
> Before running the uninstaller, you can manually unregister the shell extension following the uninstall instructions specified in INSTALL.md

error at step 1

![image](https://github.com/end2endzone/ShellAnything/assets/25656892/32ac1d3a-6fbc-4a0a-89d5-9e0e2fac74a2)

**Comment by end2endzone** [comment] 2024-08-31 16:47
I think I have found why you are getting these error messages. I am able to reproduce this issue!
If you try to unregister the shell extension twice (or more), you get this error message. In other words, if you unregister while ShellAnything is not registered, you get an error message.

Reproducing steps:
* Install the ShellAnything version 0.9.0. During installation, select "Register components". This will register the shell extension.
* On File Explorer, right-click on a directory. This will "load the shell extension in File Explorer".
* According to the uninstallation steps, if you do not want to have to reboot, you must : 
  * Manually unregister the shell extension with `unregister.bat`.
  * Refresh all Windows File Explorer processes (with file_explorer_renew.exe) or with a log off/log on

At this point, if you try to run `unregister.bat` again, you will get the error popup mentioned in the previous post:
```
---------------------------
RegSvr32
---------------------------
The module "sa.shellextension.dll" was loaded but the call to DllUnregisterServer failed with error code 0x8002801c.

For more information about this problem, search online using the error code as a search term.
---------------------------
OK   
---------------------------
```

And if you proceed and uninstall ShellAnything from the "Add or remove programs", you will get the original error popup :

```
---------------------------
ShellAnything
---------------------------
There is a problem with this Windows Instaler package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.
---------------------------
OK   
---------------------------
```

During the uninstall process, if you installed with the option "Register components", Windows Installer will need to "unregister" the shell extension. However, since the commands `regsvr32 /u sa.shellanything.dll` fails, the uninstaller also fails and reports an error.

**Comment by end2endzone** [comment] 2024-08-31 17:02
@Unknow0059 
This is quite annoying... and embarrassing... I try to test as must as possible with the installer but I see that I did not test as much as I could the uninstaller. Also I suggest in the INSTALL manual to "unregister manually before uninstallation" to allow uninstallation without reboot. If you proceed like this, it is a sure fail because of the double-unregistration. Man... I am sorry for this. Thank you for reporting this.

The issue was introduced with the partial fixes for #115 introduced somewhere between v0.8.0 and v0.9.0. I migrated my code from "do it yourself registration" to using [Microsoft's ATL::CAtlDllModuleT<> template](https://github.com/end2endzone/ShellAnything/blob/0.9.0/src/shellextension/dllmain.cpp#L128). It was supposed to be easier to manage registry modifications.

I will add this issue as part of the mandatory fixes for the next release.

**Comment by end2endzone** [comment] 2024-09-05 20:15
The behavior observed above seems to be the default by Microsoft.
For example:
1. Create a new ATL Project named `MyATLProject2`.
2. Compile the project in `Release x64` configuration.
3. Open a command prompt with "administrative privileges".
4. Change directory (cd) to `$(SolutionDir)\x64\Release`.
5. Run `regsvr32 /u MyATLProject2.dll`.
    * --> You get `DllUnregisterServer in MyATLProject2.dll succeeded`.
7. Run `regsvr32 /u MyATLProject2.dll`.
    * --> You get `The module "MyATLProject2.dll" was loaded but the call to DllUnregisterServer failed with error code 0x8002801c.`.

Here is something I do not understand. Why does `regsvr32 /u MyATLProject2.dll` succeeds again after a rebuild?
For example:
1. Repeat the steps above (until you get the error message about 0x8002801c).
2. Touch a source file (for example MyATLProject2\MyATLProject2.cpp).
3. Compile the project in `Release x64` configuration (again).
4. Open a command prompt with "administrative privileges".
5. Change directory (cd) to `$(SolutionDir)\x64\Release`.
6. Run `regsvr32 /u MyATLProject2.dll`.
    * --> You get `DllUnregisterServer in MyATLProject2.dll succeeded`.

The first time you unregister a newly build dll, the command `regsvr32 /u MyATLProject2.dll` always succeeds. Obviously, the first time MyATLProject2.dll is build, there is nothing registered to the system. This means that the hypothesis that "DllUnregisterServer() returns error code 0x8002801c because there is nothing to unregister" is false.

**Closed** 2024-09-06 00:22 UTC
Labels: bug

**Comment by Unknow0059** [comment] 2024-09-26 04:53
I believe I must wait for a new release to benefit from or otherwise this change.

**Comment by end2endzone** [comment] 2024-09-28 14:59
I need apologies for this. I am still trying to figure out how the PR and the issue should be related. I understand that it would be preferable to wait for an official release before closing the issue. But then, how am I supposed to link the PR with this issue ? Through the CHANGES file ? Maybe I could create a label "close-at-release" or something like this. Anyway.

To answer your question, yes you should wait for the new release (which I plan to do in a few weeks). However, in the meantime, you can try the nightly builds. Installers are available at https://ci.appveyor.com/project/end2endzone/shellanything/build/artifacts. 
The current builds on Github Action are working fine but the ones on AppVeyors are failing (hanging indefinitely). I am trying to figure this out as of right now. You can roll back in the history to get [the latest working version](https://ci.appveyor.com/project/end2endzone/shellanything/builds/50676650/artifacts).
